### ISSUE TITLE
delegated-resource-management-eligible-authorizations - asks for register preview feature

### ISSUE THREAD

**Issue by joerianto83** [Azure/Azure-Lighthouse-samples#68]
hi guys, 

im trying to test out below arm template, but i'm getting the following error:
https://github.com/Azure/Azure-Lighthouse-samples/tree/master/templates/delegated-resource-management-eligible-authorizations

![image](https://user-images.githubusercontent.com/43513686/87432477-56595100-c5e8-11ea-99cd-0feea339036a.png)

How can i register the subscription for '**registered for managed services  preview feature 'GovernanceSettingsPreview**' this'?

thanks in advance!

**Comment by joerianto83** [comment]
update: i've found it but i cannot register the feature. is it possible that this is just not available yet ?
_**msrest.http_logger : {"error":{"code":"FeatureRegistrationUnsupported","message":"The feature 'GovernanceSettingsPreview' does not support registration."}}
msrest.exceptions : The feature 'GovernanceSettingsPreview' does not support registration.
cli.azure.cli.core.util : The feature 'GovernanceSettingsPreview' does not support registration.
The feature 'GovernanceSettingsPreview' does not support registration.**_

**Comment by Ralph101** [comment]
Why do we need to register to this feature, I just add a new Azure AD Securtiy Group and enable 'Azure AD roles can be assigned to the group (Preview)' after enabling this preview feature I was able to add the Group Object ID to the ARM Template for onboarding. Just tested it with a PoC user and I worked fine. So my question would be why should you do this via the Azure Lighthouse ARM Template?

**Comment by simkjels** [comment]
Azure AD roles and RBAC roles are not the same thing. The reason you need
to set up eligible authorizations through the template is because that will
secure the integrity of the eligible role assignment all the way from the
customer environment to your management tenant. It's the only way the
customer can know for sure that you need to use PIM in order to gain access
to their resources.

An easy way to look at it is to consider the delegation as the "contract"
with the customer and that eligible authorization is a part of that
contract and thus ineluctable.

Best regards,

*Simen Kjelsrud*

**Comment by Ralph101** [comment]
Hi Simen thanks for your quick answer, but I do not understand. Do you rely on PIM functionality from the customer? So for example the customer can approve a request to have Reader permissions on a Resource Group. We are using PIM internally, so I have setup Privileged access groups for request Reader right on our subscription we are managing.

**Comment by simkjels** [comment]
> So for example the customer can approve a request to have Reader permissions on a Resource Group.

Not exactly, although that would be an awesome feature indeed! With PIM requirements specified in the delegation itslef, you can give the customer a guarantee that you are practicing just-in-time access. There is no way for you to circumvent it in the backend without redeploying the delegation on the customer subscription.

> We are using PIM internally, so I have setup Privileged access groups for request Reader right on our subscription we are managing.

And that is perfectly fine as well. We also do this for now until PIM is GA or at least public preview. The only drawback to this solution is that you have to provide other form for proof of just-in-time practices, like through a SOC II or ISAE 3402 audit for example. Because there is nothing preventing you from assigning permanent memberships in these groups.

**Comment by serenaz** [comment]
Hey folks! The eligible authorizations (PIM + Azure Lighthouse functionality) is still in private preview. If you'd like to try it out, then you can email azurelighthouse@microsoft.com. Otherwise, I'd recommend using one of our sample templates without eligible authorizations.
